# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        Form.setMinimumSize(QtCore.QSize(600, 300))
        Form.setMaximumSize(QtCore.QSize(600, 300))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 24, 490, 227))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.user_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pwd_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.pwd_lineEdit.setObjectName("pwd_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pwd_lineEdit)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 2)
        self.user_textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.user_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.user_textBrowser.setObjectName("user_textBrowser")
        self.gridLayout.addWidget(self.user_textBrowser, 1, 2, 2, 1)
        self.login_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.login_Button.setObjectName("login_Button")
        self.gridLayout.addWidget(self.login_Button, 2, 0, 1, 1)
        self.cancel_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.cancel_Button.setObjectName("cancel_Button")
        self.gridLayout.addWidget(self.cancel_Button, 2, 1, 1, 1)
        self.register_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.register_Button.setObjectName("register_Button")
        self.gridLayout.addWidget(self.register_Button, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">员工培训管理系统</span></p></body></html>"))
        self.label.setText(_translate("Form", "用户名"))
        self.label_2.setText(_translate("Form", "密码"))
        self.checkBox.setText(_translate("Form", "以管理员身份登录"))
        self.login_Button.setText(_translate("Form", "登录"))
        self.cancel_Button.setText(_translate("Form", "退出"))
        self.register_Button.setText(_translate("Form", "注册"))
